name: reitti
services:
  reitti:
    image: dedicatedcode/reitti:latest
    ports:
      - 8080:8080
    depends_on:
      postgis:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
      tile-cache:
        condition: service_healthy
    volumes:
     - reitti-data:/data/
    environment:
      POSTGIS_USER: reitti
      POSTGIS_PASSWORD: reitti
      POSTGIS_DB: reittidb
      POSTGIS_HOST: postgis
  postgis:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_USER: reitti
      POSTGRES_PASSWORD: reitti
      POSTGRES_DB: reittidb
    volumes:
      - postgis-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reitti -d reittidb"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  tile-cache:
    image: dedicatedcode/reitti-tile-cache:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/osm/0/0/0.png"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - tile-cache-data:/var/cache/nginx
volumes:
  postgis-data:
  redis-data:
  reitti-data:
  tile-cache-data:
